# Generated by Django 4.0.4 on 2022-05-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app1', '0003_greetingandwish_literature'),
    ]

    operations = [
        migrations.AddField(
            model_name='greetingandwish',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
