# Generated by Django 4.0.4 on 2022-05-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app1', '0006_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
